// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVolume():Promise<number>;

export function HideWindow():Promise<void>;

export function IsLocked():Promise<boolean>;

export function IsStartupEnabled():Promise<boolean>;

export function SetStartupEnabled(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function StopAllNircmd():Promise<void>;

export function ToggleLock():Promise<void>;
