// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function IsStartupEnabled() {
  return window['go']['main']['App']['IsStartupEnabled']();
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StopAllNircmd() {
  return window['go']['main']['App']['StopAllNircmd']();
}

export function ToggleLock() {
  return window['go']['main']['App']['ToggleLock']();
}
